SELECT *
FROM customer_data

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT 
SUM(purchase_amount) 
FROM customer_data
WHERE gender = 'Male'

SELECT 
SUM(purchase_amount) 
FROM customer_data
WHERE gender = 'Female'

SELECT gender , SUM(purchase_amount) AS Revenue
FROM customer_data
GROUP BY gender 


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,AVG(purchase_amount)
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount > AVG(purchase_amount) -- This is my mistake we can not use aggregate functions directly into WHERE clause
GROUP BY customer_id

SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM customer_data
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount) FROM customer_data
    );


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    AVG(purchase_amount) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY subscription_status;

-- How many Customer Having Subscription 
SELECT 
    subscription_status,
    COUNT(*) AS total_customers
	FROM customer_data
GROUP BY subscription_status;

-- Use Column name instead of * (Best Practice)
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers
	FROM customer_data
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_count,
    CAST(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
         / COUNT(*) AS DECIMAL(10,2)) AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END
ORDER BY customer_count DESC;

-- If you want to force the report to show all segments (even if count = 0)
WITH segments AS (
    SELECT 'New' AS segment
    UNION ALL SELECT 'Returning'
    UNION ALL SELECT 'Loyal'
),
actual AS (
    SELECT 
        CASE 
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            WHEN previous_purchases > 5 THEN 'Loyal'
        END AS segment
    FROM customer_data
)
SELECT 
    s.segment,
    COUNT(a.segment) AS customer_count
FROM segments s
LEFT JOIN actual a ON s.segment = a.segment
GROUP BY s.segment
ORDER BY customer_count DESC;


-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchases
FROM product_counts
WHERE rn <= 3
ORDER BY category, total_purchases DESC;

SELECT DISTINCT category
FROM customer_data

SELECT * 
FROM customer_data;

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT 
    item_purchased,
	category,
	item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, total_orders DESC;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely tosubscribe?

SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    COUNT(customer_id) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_count,
    CAST(
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*) AS DECIMAL(10,2)
    ) AS subscription_rate_percentage
FROM customer_data
GROUP BY 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END;

-- Q10. What is the revenue contribution of each age group? 

SELECT 
    CASE
        WHEN age < 20 THEN 'Under 20'
        WHEN age BETWEEN 20 AND 29 THEN '20-29'
        WHEN age BETWEEN 30 AND 39 THEN '30-39'
        WHEN age BETWEEN 40 AND 49 THEN '40-49'
        WHEN age BETWEEN 50 AND 59 THEN '50-59'
        ELSE '60+'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue,
    AVG(purchase_amount) AS avg_purchase_amount,
    COUNT(*) AS number_of_transactions
FROM customer_data
GROUP BY 
    CASE
        WHEN age < 20 THEN 'Under 20'
        WHEN age BETWEEN 20 AND 29 THEN '20-29'
        WHEN age BETWEEN 30 AND 39 THEN '30-39'
        WHEN age BETWEEN 40 AND 49 THEN '40-49'
        WHEN age BETWEEN 50 AND 59 THEN '50-59'
        ELSE '60+'
    END
ORDER BY total_revenue DESC;
